apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sequential-
  namespace: argo
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: Somma
        template: cont1
    - - name: Prodotto
        template: cont2

  - name: cont1
    container:
      image: sumkk
      imagePullPolicy: Never
      env:
      - name: DB_URL
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: DB1_DB_URL
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: DB1_DB_USER
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: DB1_DB_PASSWORD
      command: ["java", "-jar", "/app/sum.jar"]

  - name: cont2
    container:
      image: prodkk
      imagePullPolicy: Never
      env:
      - name: DB_URL
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: DB1_DB_URL
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: DB1_DB_USER
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: DB1_DB_PASSWORD
      command: ["java", "-jar", "/app/prod.jar"]

