apiVersion: v1
kind: ServiceAccount
metadata:
  name: marcograziano
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo
  name: marcograziano-executor
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: marcograziano-executor-binding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: marcograziano
  namespace: argo
roleRef:
  kind: Role
  name: marcograziano-executor
  apiGroup: rbac.authorization.k8s.io
