apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: limit-ingress-traffic
  namespace: argo
spec:
  podSelector:
    matchLabels:
      app: restrict-traffic
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 5433
